### ISSUE TITLE
s3-server access logging unable to pass region name 

### ISSUE THREAD

**Issue by cvemula1** [davidclin/cloudcustodian-policies#4]
I'm trying to pass the region name variable into the policy 
```   
       - type: value
         key: "Logging"
         value: empty
       - type: value
         key: "Location.LocationConstraint"
         value_from:
            url: file:///.development/polices/env.json
            format: json
            expr: '{region}'
         value: '{region}'
         op: eq
         value_type: swap
```

The variable file JSON looks like :
```
{
   "us-east-1" : null ,
   "us-west-1" : "us-west-1"
 }
```
means for server access logging of s3 works fine with all regions bypassing the "Location.LocationConstraint" key as region name except for the region us-east-1 it should be null as shown in the above example 
Any workaround this would be helpfull
